# Usa una imagen de Nginx como base
FROM nginx:alpine

# Copia los archivos estáticos de la carpeta 'dist' de tu proyecto
COPY dist /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
