# Generated by Django 5.0.4 on 2024-06-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='historial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='solicitud_horas',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
