# Generated by Django 5.0.4 on 2024-06-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='carrera',
            field=models.CharField(default='ICC', max_length=100),
        ),
        migrations.AddField(
            model_name='modulo',
            name='historial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='solicitud_horas',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='promedio',
            field=models.FloatField(default=0.0),
        ),
    ]
