# Generated by Django 5.0.4 on 2024-05-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='seccion',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='otros',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
