# Generated by Django 5.0.4 on 2024-06-04 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_oferta_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modulo',
            constraint=models.UniqueConstraint(fields=('nombre', 'seccion', 'anio', 'semestre'), name='unique_modulo'),
        ),
    ]
