# Generated by Django 5.0.4 on 2024-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_resolucion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolucion',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
