# Generated by Django 5.0.4 on 2024-07-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_oferta_fecha_creacion_postulacion_fecha_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
