# Generated by Django 5.0.4 on 2024-07-02 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_oferta_fecha_modificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postulacion',
            constraint=models.UniqueConstraint(fields=('postulante', 'oferta'), name='unique_postulacion'),
        ),
    ]
