# Generated by Django 5.0.4 on 2024-06-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_postulacion_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='promedio',
            field=models.FloatField(default=0.0),
        ),
    ]
