# Generated by Django 5.0.4 on 2024-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Promedio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
